theme: jekyll-theme-minimal
title: Students@SC Resume and Portfolio Workshops
description: Supplemental materials for the Resume and Portfolio Workshops

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
